describe("Onliner.by - Catalog / Products List", () => {
	it("default sort order is set as 'Popular'", () => {})
	it("user should be able to order products", () => {})
	it("user should be able to filter products", () => {})
	it("user should be able to reset filters", () => {})
	it("user should be able to add products for comparison", () => {})
	it("user should be able to open offers list page", () => {})
	it("user should be able to observe user's ads", () => {})
	it("user should be able to create ad", () => {})
})
